apiVersion: v1
kind: Secret
metadata:
    name: registry-pull
    namespace: dignita-crm
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:ydu5IW6/5yJNBRbR7Ii8W5aMj/PmM3ygTMrrEajYRMwzn4+mmyMKzRmZc/4BEFei7eSwHhV6nQFbcy+jH5mjAag9Xb9/wOyp/gY=,iv:xgVbX9HSlYmSCUS4igf9wWqzr4UucCTs0vjoT+IMPBg=,tag:8rS1YMSh3V69wiLzr4rI2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOFZ1azVmVHppcXNVYUdz
            UFFTb0Vmd1IybFJMUzZkNmo5a205RU1yT0RBCmcvaklUUEJnZUF6ZWZzZlo4NjBa
            WFlYdFZhelRVV3JnbVN3RVFyenpIWDgKLS0tIGpUeWRORlVXTk5PY2dtSVE5aExV
            SW51dlpJOXJ0ekRpSm9Ca2l0NGxvM28KXoVXXlaraijhYcXQObY0OwJayVFbPBvK
            McaNscZyNwUYsXwIPwI0rKQ299U3QFZJreUJ2/DlpyR65LsrOoCoaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T11:55:57Z"
    mac: ENC[AES256_GCM,data:CdF+/Cv7Tp+cUYxiUTXCshdX5VE9m2XDPdOTREx1652TnifSKKxXB7vklENgeikPOqqNqJpJ0XL6sIU0J3Q7bGfiSjci/Le15MbGh+OILQ8XAVrTqwHmvNdOcOndKivsp1P11e5QbXl1mcBPrE7aGioHEyWZ5RQuD/qOcsrP4q4=,iv:UEKWODsMEvscEWTHtRXD94wAJnBrL1aK8bqQ2oxxey8=,tag:Gc5/NHUMmtH6sptbvmzKyQ==,type:str]
    version: 3.13.2
