apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:qkumywSE3dL3Oysn5Hx7TKlrCN9BdjGxeBj6sg==,iv:KZgeT8TZj4OaEjASF/AGudvxlHay1pUm70BWVcws8bQ=,tag:KmN60D3HZebVFqZg3ERJgg==,type:str]
    AWS_BUCKET_NAME: ENC[AES256_GCM,data:NzSM1Kv9Z/7BiF0TJ9yHF84njhM4UXIx1tglpA==,iv:IyNOzYIlPEC7jF86mz8xlfxt7GoOlATCFDv+pU1I+8U=,tag:P0IPoepyXskD/9ltTaLykw==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:E+1rHlrob+I0HmsiZITamQ==,iv:NntssOlXJe0Qy6WwBJyl6vCMtDz0/LIsJF22ggW7D6I=,tag:VqSv1LuOjSWNPQi2/Uk2fQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:kagX+3yAEak/3BunqI6XLipyx5v/1ZW7lSfKouVhZV9lqK+NwTGItaN5IZb7lC0/LuGBGBI5jLE=,iv:x+nle0SagkoHVX0CRG7PaoynVAxVP/EW4cNV+ccaM9U=,tag:gnJ2XtDLVbnIVZmi8NSlIw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:xnd/J3viLBYqGT+CvSlmTBRzLyvrBvnLaNh+r0AZ7pVDnGhuXeCpa3w7aR0+9Y3vHWcy4twP39e7G3CUxcyGDFhWvyAkOpMx1dudmFk+Ujg=,iv:OLZ+Xz+/d4g9o0xxyBE9OC2FBtdw+yef6Xypc2O1WWg=,tag:4JPXdocKSNy0gmoPFLNM/g==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:YeOTrTwuVx8WmqFiMt81xuHzvoY=,iv:tter63tQYQ7ot47pagcB3AABvNIGUElG05Zk8VogA9Y=,tag:Dlup8c7QqTFnG6XCYbZUAg==,type:str]
    PASSWORD_SALT: ENC[AES256_GCM,data:luQRy6NR8I7oM3adu2g3uqU02ss=,iv:SBRKSCypfc7QXnYs3LsJ6/gxKUb2QEXIF9UjmuueAGg=,tag:LPFAsJL40cHejPNYzkWm9w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Iy3mFPC5/CGeBfu8,iv:eKe54OO7NtvZeuo1z3BZZMEThGaqcaurYw0lL5U75Ys=,tag:87XrSXGbxgVn1X8us9xj4A==,type:str]
kind: Secret
metadata:
    name: dignita-crm-secret
    namespace: dignita-crm
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMXBSQWQvZmh3OVRkRjBv
            L1R1TnNMRWFKNERnNG0rVlBPK2FYbU5aUFhNCjArRUQyUjErMm1NMlE4Y2ZSWm0x
            M0l0bTBNUTZtTXJoNkVGNmk4N2x3V2cKLS0tIDhUVVYwNnhCV2svRm1VVzVGL2Nv
            SktaYXJGRnRLQ1MvQXl2UmsrQ0lkTUUKzT7aI+USUmEH4/QwYU9FdYuM5/QuUJDB
            vWJP4QbZqvHKSNkwcQp17DWT6YKYJWHFl9OY8QObCpOc5OAa0xV0fw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T11:55:58Z"
    mac: ENC[AES256_GCM,data:3PKiS3vU7/O7Q63Vi1iLUVJgbF608GSkvCwr3zfh0u6f7piydxhMwVuY5ZYJOxfvZZhAqNyIKIhPU3oumJuU4pifIqYm5KYBnkSTYp+noVzxhhqPnYRKYkpnfExi4xd8rvpV9SO29OvrKtQ46lJ73fT1VT4W48RjAX6mS+eGXcM=,iv:9wrASHgHbONEzbrvlBzhpOdAI2EfY4Tdo0mn03vK9Z0=,tag:4MYHp7YKG9l89zSO6CBzGA==,type:str]
    version: 3.13.2
