apiVersion: v1
kind: Secret
metadata:
    name: registry-pull
    namespace: portfolio
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:0H+POfD/9iNbB4dB5169w5Dnb3Gvjl2UiNdMbXckV18ePBZwVdeK3Yu7d4DpaOsa+4tx7xRkx5EEl5q0lN3M9vc94n1pbwDooDg=,iv:vs7mDKghflfepHhAYJKHYplsGUz2CHNR5PjwWk2z8ZM=,tag:TXSWYMRE4dMww3Mz6tJUKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsc3BoajNCb1VyNHc5Zlhq
            NDB1aXovaW9BN3AySEsvK2hIM05IQ3lFUlNzCi9Ocys0OFFtZUg3dFV2V2hpSnNF
            QmZHaXFDVnJYQjU0TXRGSW9aNFVtNnMKLS0tIHgzUEV4Ky92eUkrbGpkd3VzRk1E
            TXNLSUdhYVBWSkNnS01UQ25lZGZpRFkK1rcvX4aZcpjkcxV2tITYfhZPtcAyjm+K
            uzcb36wLv+z5ZY8zRk3e3DgEYyH7+/rh7UR++no9g74AXE54BQzkPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T10:07:28Z"
    mac: ENC[AES256_GCM,data:9ACxg87uGvgxm9rdih9s9c6kDRVz0JkalSTQW4R3ekUwZ7Tv3P7A/xG/orSQKUAdaml42r8irlZQ+BayyLD5A1dwLceuDk0NZ2qP8h7JgOWlGJ6T1AdfS3dob8ViG5vfdOYVaYSMLk3zyev3P2gLG1afyEVUwnAUiohJc11jTjQ=,iv:MAAtmGA2c0Xd4kkuRLvOauFH1akEfak1qBHn7Fih80s=,tag:DWpx9yGQ3lq4WCw88m/76A==,type:str]
    version: 3.13.2
