apiVersion: v1
data:
    ADMIN_ALLOWLIST: ENC[AES256_GCM,data:dNYxqMckihUQW9srUj6LEGh2e5kPZmVMHWO9QsJ6L7ebLjuvf7Lfa3psVnM=,iv:frsaorZ5B7k9V5ti3eFFA8zCOSVOhNS7jGYrss9NPGI=,tag:bnpw/pM6wppPe24mBBE+CQ==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:fanZvhazl+DnczxdKn5vUsGl/XJI9qKstwgJSfS3ezRfVf7dUlZlYKVj4ZsS3ygUi/Qm/VUdd9k=,iv:iNmKaMwtgkmNWMVEgu2zI6YJfPXMKo71sXDNkwsq1Kw=,tag:oRKm30122b3fUPSIN+xnxw==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:pz44fCQ5bmU56astR7IXQfmgityV6UI3OpcxPQQu9q7oVoTG,iv:fPCj9MHLV4V2JN8Ezo7PI7bvFp8Z4JyV4KXo9lAYbQc=,tag:Lyw2KTB0lUXwrK6BVtdneg==,type:str]
kind: Secret
metadata:
    name: portfolio-secret
    namespace: portfolio
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5b3dBNDNSU0gxdTQ4QkFq
            OGJ5TDZOL2Z3emlhRUNHcEpleEp0a21FZlRNClIwdEIwaFZTdG9MeGJ2T2I0REFH
            VGY5d29mdkZkOFZjcFEvNUxCVWN3MWMKLS0tIFo3eStUaVZkV1dObHJkckErVm1O
            M0tlcXRSQ1lYT3BQdkVuSFowa1VOSjAKNWwcpCSBlYA8UWBqPFYjZF2MfqXEehpi
            35/kYUy5SR81JpxE3csfW89LJWVSbU3RpyrNyO7rToxe7f9zP9X97A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T10:07:29Z"
    mac: ENC[AES256_GCM,data:rJjMwqrQLblDgEPsdSRoSFQxql8hqwNEAs5I99a/1Q8/bRaOMYb64LdSvM9MdY947MyAyEV0hYBUQgp+dR45WpZTbtRPO+PmcCh5x+AMpfpe4Berd3Y98bih4vt298vRXoe5Q/NrvJCvG/vpnZAGoREGdZWIx4gNJn6VHB3qQiY=,iv:WSDkq1JrCq8eFikkRUsM0/rY9kLV1DOrOFdHxiiVSIY=,tag:UBB69QABqNIuDmrt1MYBcA==,type:str]
    version: 3.13.2
