apiVersion: v1
kind: Secret
metadata:
    name: registry-pull
    namespace: abrabus
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:zmOIZXl6uE3G5P7yal+46O03AT0xnT+TLNrtv3ujjvZQOm0KbY6AZogCGAuqjgREudZOiW/gFmc0KSX2VhDyQH464W3wuaCKzFQ=,iv:O4ndDCzL3knGRzxXgQiRsLtK5jC51GL7OS8zUAAVAKs=,tag:TnR6tadLW0jraY06fAEEsQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTTRZU2NzSmVNM0dpemJa
            Y3Q5UnpDUVRUOU1EUGNKcndaUEZuZUhtTHhJCnI2Uk5jaytiU3NCVk5hYUx5QmJK
            MEtrWkFZRlJWTkNnZW9Ud3QzbVN5YXMKLS0tIDRoQWhvU2JRc25TclIzbll5Z2Ju
            R25IV0tFZFhKaldOZkd5U1JrN29Fa1EK8hM3Z1jlqV3873xgviujUf0QdeAkveGm
            C9DHn9gjE3rlyHxIwJIaFWjx/2MaCWKROS04lHRaK3bHNu2rJp8F8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T00:49:57Z"
    mac: ENC[AES256_GCM,data:DNDDNk1nnG5YBA9qLZbrpwTyvMO+G/m8GEdcPsNMsEY0M+Q1jsc/hT5oWU2Y/lKMoZPB7sCdBxqInooakTz86u1f5flNQaLSvgB+gwVhtHAp8ABk9nJ8/yRdHT3VFtdeur7lTV7dJFGBsAK0cFHQvpCZ0faY5bEsMuzsdEQIGAM=,iv:lcvn7CeeJQ770EiuqdabAuPoNxKBHuYSYFzchy1TuUI=,tag:0HG1DmiPBoSs6J7CwY6fWQ==,type:str]
    version: 3.13.2
