apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - namespace.yaml
  - secret.yaml          # SOPS-encrypted (copy from secret.example.yaml)
  - postgres.yaml
#  - helmrepository.yaml
  - helm.yaml
  - certificate.yaml
  - ingressroute.yaml
