apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - cert-manager.yaml
  - metallb.yaml
  - openebs.yaml
  - traefik.yaml
  - security-headers-middleware.yaml
  - cloudnative-pg.yaml
