apiVersion: v1
kind: Secret
metadata:
    name: registry-auth
    namespace: registry
stringData:
    registry.password: ENC[AES256_GCM,data:7xOws1M11hQ/oao6e9DhIUxXr50YzXkQzKtRR2i8/rPdMqsqO6R3W5jRB625zljXmVuME6sGUN3/N4GLH/tM94Byq2U=,iv:mjdBlejEmVcoe/ZHv+roapU+WKehtuKa3eQubFKDK+s=,tag:gogpbmimnIo3RdvXX+iJEA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaVBzVGtqckhsRmJmeFZW
            NVYvaUhFQjcyM3BBZ01WTkxDZ21DUmRhTFVrCmZVRkgyM0YxZnJ2T3NFKy83SUgv
            ejdLbkxmUWVzUktPekozSm1nT3Vwek0KLS0tIGFNNHhNYllwb0hxVXJITzhUazF4
            YlY1NHBQYkpzcExPZ0tWZ0NkTUtsTlUK8G6JHoqTnKNhV9RnEyi9yXOrVRve6gJj
            FacOgmgOfoz4iU9hGhLZQucaf97WcjX5oyvfzPGwxsiRjVsvLnIbfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T00:22:31Z"
    mac: ENC[AES256_GCM,data:kQ6AV4L7csT/++16LLDKboUJdFTpV/aWomD94X7bGNPw75TgZ/wug5k1QPYVbdXw0XpA7CxP47wOk7ysgqwhESPay3EpC2iyxHJbNSWXeLYeVBy/H4+Cu5baxUP36nKnPCFdPefT/9I75Ph3Pc9qXrI8KxSSzuYTOH7rl6eT+Y8=,iv:hBM5kFbtW2T/CJAdWmHyL1CXSD0Radrxb7Fe9cA+1IQ=,tag:i5HXn9LnOkBc6UO/jLKwFA==,type:str]
    version: 3.13.2
