apiVersion: v1
kind: Secret
metadata:
    name: dental-website-auth
    namespace: dental-website
type: Opaque
stringData:
    AUTH_SECRET: ENC[AES256_GCM,data:hk9tPWSc+ZT2sLVufXUUOAmbzPkS2oUXj2Ah6mBcYHomoAVGJ1QSJVuPXGc1QZKcaNUYUzeChmQDuzC/fF4dBg==,iv:1dyYL/OLbw2NpnHC+Lr4X0LX/FUuIc+1LHTVnO58Z8w=,tag:sPGbf6B9ufmeOAY1G8ALJw==,type:str]
    AUTHENTIK_ISSUER: ENC[AES256_GCM,data:QUf8+ECpLq3XIVkwZV1qGrzj4kymioY2XP48NZUpeqMjq3hOfp2IPLphzUBoPLBcCGpZ,iv:Xt9+YI5KPNhcjVWLK+IBBDwzOBJIztLcBgRkXXIVswQ=,tag:0r+8AByynwAotbFWrXh25g==,type:str]
    AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:I67kANZOoBjg/WqIvuNqEPE/5TOAbTT1+oyX9gVPyj2XaGUfTpFz6Q==,iv:9dA5N5mSeJVHuBDUSboEWse6LER/gfEDbUQflN9MWGg=,tag:2iJgR6qmOX1394sDcHND2w==,type:str]
    AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:jXDYTiRJZHBkc+10kVZO3NEXshPoNsHR4llN67mx4yd53DPRfouXOPadPvFc4y6+X9j3HWWydMQub+HO9f/Su5FYsjS53F1/2h8qVd/xRix2HakDihbpQZ4OpTsUk40ivcPqBRQAJY4HxTd3Vux7TNRIuutvSn2NZQFv1HIqADk=,iv:amunIi7kyjQU6lTcRbj/WCrKBsW9ITAqDQk0Ro1CoF8=,tag:xP2LHko4zyDhIUtxfyWoHQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0YmptcHlZblpwbU13WUFl
            UUFVSUs5TWdNVnZwQXhNYzBkQWRZelhzUnpRCmZRY2daV1UvOUZ2MjdsNUNCUUpw
            eWhTYjcrSFB1VnVKRlU2bU5GSHBjWU0KLS0tIFJadkFqN3pDWnlobFgxazlsbVFa
            TU1ITFo5dU81OWhhMzJHdllnRHN1VTQKZ91eeTH1Ef2gVfMIUOA9o3DJ4HHmzoQu
            nzE2C0pQz/GoKrCBW0ABmQ42wU2uiU1ob3fBg6pqagaYdBThwMB9Yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T14:11:19Z"
    mac: ENC[AES256_GCM,data:gioFsQiSYoVaDgvtOLCH2GMLH69w/zQh6HyGWlKh1AOZ5asE+V3ONWCiPQqL7OxBFdqTIsp1ktAdfrWcLK5A4sNveofGeGm2ox143sjOhqLg+TV7270/lDJf9rqxO0tGlF+Z5DvBXzKzxAJ481oayTI2vZIbSIlV54iZnk+dQac=,iv:JSstfGICReCV2P1YotT3EPyX3uEnAj1XZ6HXd75qgwk=,tag:6JC+MajfMs2G/RcepsTd3Q==,type:str]
    version: 3.13.3
