apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dental-website
resources:
  - namespace.yaml
  - pull.secret.yaml
  - auth.secret.yaml
  - helmrelease.yaml     # website chart: flux/charts/website
