apiVersion: v1
kind: Secret
metadata:
    name: registry-pull
    namespace: dental-website
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:Bn0fgs/3ilmIU8ddDo68y9z4+tIYpBSqnPRELaxxHf0n2HTmO80q1YD4/Suus+QZyxWQCOc9XvX0LMrCYiM1azTydfvzstBnPsk=,iv:5joBuhPC0E+7vOrsl+3+ici4ltzzsU1yFa7yMg49M/8=,tag:3kgdZmZof2OaMBavtVQIGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNjZYb09BK0NmUlZHSVFz
            S29qaS93ZFBnWVRGcjRuV3dyV2tESnNCY0ZBCnczYTdnVG13ZXcrNDN0Tk9ob3lo
            MFZIa09JOURWQlZOUlhYOXpRaHp0TjgKLS0tIEZTUEVOTU0wc2xNVjJlZHVlV1d1
            akFrNEJHM2xjbW42VHU5NytYM28vTncKRrRLfaCpCPumYI4AlGoDgU4Z2+eNa2/N
            8ryHIfRlYOnz7MdUJfy+aMormTdnsRorwEE8xtyGIEyZcl0OZEqQgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T14:11:13Z"
    mac: ENC[AES256_GCM,data:7lOkge3yGhCif2PlrhNs67HThlAT1vMWVXTkjBOO90tvgi/hQ7V5pVZA6tmWaHjEyIq9ZqBXVYlSHjnaruEYgDI9pB2ctVQ8oZE8DA8FTB2fxUFfM6JFt5Rer8jl/8qhz2jt7oy46SqSCVo60VkkF8kleyP6+DFB0ZSCrc0Gnrc=,iv:xN+v7pvo1qTHp3AxlT61qwNy0sLZiEZYOw87+II1cQc=,tag:i+duuG34wcz2pyVkLf/5mQ==,type:str]
    version: 3.13.3
