apiVersion: v1
kind: Secret
metadata:
    name: registry-pull
    namespace: johnjtac
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:JeqXodZPS7YgpxGKhDtLnuFYkrZgKP+vhiZl4bPVJnHM6Om65lK9fVx6WIVvLwviBGm5O61D/o1i+05a0MEWUTHoLKx77s0zax0=,iv:ALL1xrCl/56AnsyuiwROw8kGyGTVJict00v3r8kZt7I=,tag:ffXFOpalBPvcuPJW7wmiqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRWNpNjFuRFF5TlFHUjJC
            MEJHSHVyZmZpTE9JeUpMSXRDbk5RNVhkUEFvCmVTeXFDZTZLeGxZRVVUMlI1dlhm
            dW9XQjNDSmdFZ3RldHFLNk1UMzd6NXMKLS0tIGl0Z3MxZkl1WDUvcWU1aTdUS1hx
            bXpGK2JESkRKYkh2ekZCaFE0U0k1Z3MKCXOtBEsBPxoPvy4mDN+xzvuLGS5OrmgP
            5E2XW3U5gljf5YpPmPhcg5NZpw0f/kcpB5QSiwF91SawrXO3YaKWbQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T10:28:25Z"
    mac: ENC[AES256_GCM,data:eCV9qqsu8jDDTNGOdclSp+vIahZKuVayDxv1ZD2eNtbOMPCc7OVbbPBKVaZ+9YSQwIqgoCXv/jIruxAvAc3bx017mRDrXvijFxrlS9DCO5aDQRCEZMjpnlRWC722ZgKDwG/1/4qdD4daGfU6rpTE5acFsgcH2FKjxIyzIZbHFcw=,iv:CXADr5CdhH2G7dKtmx1GzyHDnsJVjxcNznmtmOoyPbQ=,tag:qb1XmPIOVw75O91Koq74sQ==,type:str]
    version: 3.13.2
