apiVersion: v1
data:
    DISCORD_CLIENT_ID: ENC[AES256_GCM,data:Fp8mjUqf3vfx9+DAGmattOMBPMkAo8tbInjR1A==,iv:AYmovFcWu1LWziXrbUupb5KRS+BvrdTors5vmcaQI6U=,tag:BvrYKTwgPPkynq/tBI0Hwg==,type:str]
    DISCORD_TOKEN: ENC[AES256_GCM,data:ofcVtyyTj6V4FT/EvCjzXCY1Fr7D4rmBc779CfBivIJYw7ha0RcVumfMTHzTMDGCwUDYXNr7jg/KJaIN3KPXVU8NKmVuukCpbKAdrlDJWK8zBp/3y/loolbYxGDp88Dz,iv:8K8RLXw8oH6GLU545IA7A0UBhNd18hrMo8Kenkztvgw=,tag:AGxKqn9h7mwiRcbKEOhEvQ==,type:str]
    GROK_ADMIN_USER_ID: ENC[AES256_GCM,data:VtWjKn6VgWB0Wq1pWiHQ7krE1Jv1SHf3,iv:DJVUBCUkYmW/uNg74n0BupcZ/Rpl7u807xlQnehzxMg=,tag:Xq98iof6ZjwN5DDwtWIjvQ==,type:str]
    GROK_INPUT_PRICE_PER_M: ENC[AES256_GCM,data:lMxv/g==,iv:4DtJ6qOLALjZKLgfpCW98Nt48v4IgqoahtEuzSCx1QU=,tag:0H37P68/Ouup++v8V3mZNg==,type:str]
    GROK_MODEL: ENC[AES256_GCM,data:KbpzoS/AASdcxdglNre4Hg+DjdRJ4cWrn95p3Kja+dI=,iv:3AdI+aS1EU/e9CD9vOpsm35yhdqWri2ydT41HD8HIRg=,tag:EAA5fXlubwcUNk3zeFxhrw==,type:str]
    GROK_OUTPUT_PRICE_PER_M: ENC[AES256_GCM,data:GmAI+w==,iv:qaaxWdsujjJy9W5Sed8atynPgazOPxC0DexOgMUmZbE=,tag:+fKD0ESXo9bpZOuWL+/aFw==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:tv53b7kJXOs=,iv:TIV9s40PmLQx9PQfAuUPbi5K9hziRHW0Hb2VBxdmcWI=,tag:9Vr4DJbF/m5C1g0uRyZ4Yw==,type:str]
    XAI_API_KEY: ENC[AES256_GCM,data:QlJW7eayHYcMyo2HF6bAniXjDnERwypL+J7M4y+hSJXDYPL0GDZaCj4tQAWSEMm8Z3Q1lLRGzZ+oD8liLsrUmgPuitrEGSspsItRjrMS5xjmxTggJO5szNJofVysSTvNn8Wf7hXpqGY/I+SJfDu6BQ==,iv:DwIFIWKTy6deTHkmB6jA5/8Q6mEZ0gLfa74wB0J2TRc=,tag:DJ7EWAiAzpBWXLwhjGkcUA==,type:str]
kind: Secret
metadata:
    name: johnjtac-secret
    namespace: johnjtac
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWE5oZmpVNzdqSjV2bk9F
            V0xaNWpvMHorYVV3Rkk0ZlUxNVNGK1J5ZlJZCnFyMDFOV2hmUGpzWTA3STlNUXpG
            NlV6OXRKSENVendTRENNQ3owU3hiUWMKLS0tIHJqeDN4c0xtMHpwNk9PZmZiQ0tS
            czcvZ1QvM3B5NHZwTmZSOFc1OHR4SzAKzaAPtcJcdxJHlt0Bg2F1L7qW0PUfc/fQ
            YPOJLZn6cpNF1p3EOVUJdlUXCrW9NT+ul8XiYmq3jrlJnYqUVJcuQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T10:28:26Z"
    mac: ENC[AES256_GCM,data:ppLKwx83fjD4cdwDKFXjQiZWxp8mRIHcOUuaMpiJfeU2M91jEvKFxTT/k1mf+en2ZIoMjc5d+WJitjScTmz/e7ZOgOC/4mFlLnSZhYDXiG8fjSUN8blNi4x7uTDOixAof3nnc9/BtvcOzuTn1lqJ9DelyME8c1hKWqPofGANHQw=,iv:TJAIiij4T1wgvjwe6qc5xHP89PzJMWzifN3HC95srdQ=,tag:Abv9WFfbQmNnDBMz/je4UA==,type:str]
    version: 3.13.2
