apiVersion: v1
kind: Secret
metadata:
    name: registry-pull
    namespace: sage-ai
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:28WYL6+7j/X3sVl4GVZFsUxzn/yHQ0RIYodvYba97C0Grw7Ye9KoaO/qBMHKEj86vgF1nv2YidaEYoM2ZVbADOjMFqnVZ0QCvBo=,iv:kjPUssnthHlsCTCPtn0QrfMLruYGISG+bW0u9nCzT/Y=,tag:FdaIeNZAUvjNO5OKABLg6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaVpDeGpNbGJ3SHhKYS9E
            YjI2TzltUjNiMXp6Ky90L3p1UFNQRWRiZ21jClAxUFRkUTE3RWRuaTBXSHpkdnJi
            Y0Q1bjEzV0kwNFpOUW40cjNXQlFhVWcKLS0tIEI2S0pwM2M4S2UwM3dYV1pJQ0xo
            YU9qcTlOTTBEZlRSQlJwQzZwU3dlcVkKtLrsVWy13l1TNjP1G76MReKVtPrqUCoR
            6J/8CMoL2WROEgRT/EB8+hg/UXLTc8ezZmrqhHEcqp7cIW/R0MF6Rg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T12:09:56Z"
    mac: ENC[AES256_GCM,data:UlNULrp0pez/fS6dSDyjXhg5RSKJoh4I4Dvqz3OnTuL0yl37OPFWwcdTKzM5N4I6u0k1eY17m58BwLL8TWb9xuntpmIJGK2bTC+XmgLFXXeMkBSUOtBqqp69Y0eUGTGUh50/au9nTQCs2fbdGXboQOb3Keyho7HdkHPxJRXomZ4=,iv:KwahivaEwgncBJJoUAVdG+E73CryDgq73ZDdPDNImP0=,tag:rpW5+f+t2Se0bBdGe7dapQ==,type:str]
    version: 3.13.2
