apiVersion: v1
data:
    DB_URL: ENC[AES256_GCM,data:I/CrqFKHjzS5V5xohvC0OVu1WLezw4ZFqX84mEwNvEouePoa+gzmlso1S8en/fQEmqJmeehqPDW3OMCZkBvgjo9kiLXKO3axy4hwJAhsJW2+wNwGAD7XxBOyUYg2njCAUYhjICTOgwEe+FTP5jj2+cdQZRqSwZ8p5eRNx/b9Uk8/GeLZl0daO7NZTKnnHOVEea0vsQ2RG44iEgpBUJVX0X+JNcP4C7l+foeynw==,iv:PJO+nk1l6X0VmRus6ya53sFWJ2NQUT9cnHXOtOIeDuw=,tag:d71vqH3/aU3bkmnCmyYtdA==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:s9SZxli53XW1H1+gX0XZ2A==,iv:K/S049Fn+G6jZyiydU92Z/vM9abamL221TwTO7VQGSM=,tag:mblDI3j2RJ3W+sVa69Gvxg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:rwszWfVJ1PvekNmiP+3g1Q==,iv:NxDTkFwXVh2/EIOjz3PwXGuTiKe92nY+PpFznA27rHs=,tag:FoZNJIHZIia1DrZdib43Ww==,type:str]
    MSSQL_SA_PASSWORD: ENC[AES256_GCM,data:TlLJEqjZFvcMjDQ/UHNPUg==,iv:qnEuuCqUFLj4zoQk1uC8K2SHZODDxq9GyIivjO9KPfU=,tag:D3HV7k1id6y7DCe54qFSpw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:JQH79eVT1Ul65liB873ttOVYfn7qlBIVDBodBlui5d2EvK5xaY58zREafS44PaNVaJ1/AzhPXpk71APlbMueGZE+Ystm9JeNrg3wYsqlt8cHmyETxoJAcXeFNbBrUOGXIfWqtS/PGFIv0+hDm31dN+RMIZL7AJWIn5LBS7aL3KXYNm+7PO/z8LH0d1MjK+AMM8xFUqeRDVfYFMhpdHm5JuLsjZEnRfYj0sQbZj7D7OhOHIm678QxwS7maMOZ2NNq007cM6X2Hfh4SkfFeHNYDYRpP/I2IGvfzCzZSg==,iv:ovW72/JHerk1bDkUyJgqNJ70Z663fRKilA/gZIsxyv8=,tag:ltwBuggBDFrydX0/SdGqjQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:slgPDTm0i/dY23e8,iv:/9B3+acubK7HywTYQiwlK5TYNWoEdLYdPa4DpmCNEbc=,tag:Dm5U+rst8BxIIWAosDzWjA==,type:str]
kind: Secret
metadata:
    name: sage-secret
    namespace: sage-ai
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYelgzOERaNmtXSytNczFj
            ejAwYVdIOTU5ck9nTEY1UGU1dHQ2TXdKNkV3CmV4eENUelZaSWlmYmVudlZ1b2k2
            U3J2aVNJNEhuREdYUm41bjZqTVNMLzQKLS0tIFV2Yml4T3gxdmhMM0F5eWE4dzQ0
            elkwbEZVR3VWVHg4WWJheUUyN0hKSjAKrHEAgD8TTfqCivoNXQ4zDhxS5AYyVL3x
            OJdx4eUHYT+ejTm2q/Wi2iBR6IYAzIjPIeoimdVpSGvsFw75iuwxPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T12:09:58Z"
    mac: ENC[AES256_GCM,data:rjqW7WPEPElxiYR3200J+IBPWn1Jmzdiubx/EGnNPssrl/0ZNArx9VFTQk+/Y+rE4hMXJBj8coLf+SliNGcPdUR1cGqMwD9aNXXuX0AC9eOGqCLgRVQKC+iNrxKYj4KUR6iLdbCWGw2B+BYwlxslwJek3MyvO9z7jCBjr6XbwM8=,iv:rKiXgMxAOJC9cbGhVhpxKgIjInfej/jufr06SqKlKzk=,tag:EuKXlLXRpVDQ485BrosyOg==,type:str]
    version: 3.13.2
