apiVersion: v1
kind: Secret
metadata:
    name: registry-pull
    namespace: aquilla-website
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:eNV5LYeROdnHXVp8owc/GM7ALrBkpCFa+ZsJy41UhLkKHr0EVdlcgt1yIfzBESqpKttNCHwnfdM934qhT8YgaE9A+/YWKWKu1bw=,iv:JqI3ZZzRpGl7q9MhanNgg4YCBK5qEKGC6lasLBAeDtU=,tag:SWbj/OHkruCEBouaSlgcjA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZTRCeFk3c1pwbnVBWDJv
            VGptNnFJc2haNWRMYkExQlBoUFBXQjlxRW5RCmRsTWliMG8ydWpOL3plcjQzNlRn
            TXpCNDUrMzZGUlA5L2Z2S0RMQkFoVWcKLS0tIFk2bWtmSkQyKzFkSzRBUTJCQlY1
            S04wZ0tla0YrSzlyUnJSK1pTcVpCNWcK03Ty/KE1wW9MDQBZwdeT4DF6cHRCwAqK
            07PI8OK7J3Z7ttELJDWq+HPZYyFhqLuCcTVoZLck3sie7aPn6gFQgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T00:49:57Z"
    mac: ENC[AES256_GCM,data:mw0KmssdCmRAZBzT60X3oN4Pg9YNyXXXlA8lDZbedf3zP5oou6bw2jqJvVqwRqrSD5FmMpUd9MQJORSlu5exOlqAZBMh+xhrvIjreHp6atZvFBTy12c+th70dJy6nrhPCIHhyXusjKcackJt9RPu+QcNQsno4R/CTPy25cUmBEY=,iv:ZUzIynnQwV3IAjfXU0+Hev6eTSX6OjoF497Yu2gF7dE=,tag:OZpdsb5lC7k3jXunARTi+A==,type:str]
    version: 3.13.2
