apiVersion: v1
kind: Secret
metadata:
    name: aquilla-website-smtp
    namespace: aquilla-website
stringData:
    SMTP_HOST: ENC[AES256_GCM,data:3IqSXZqXjwzygra5GRWqOwi/bg==,iv:FGFCoGx8mK1rRAODG+r4oIf2rsUOfOJYMslNGJsyNOc=,tag:Zy4dAE5V3qFGVhZQUIIenA==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:vc+E,iv:P7zfHeKQORLDQtKC9MQP33fZ3tuXFTkSkXhzzMnqon4=,tag:miFYUReBIS6Otq0872CnnQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:HwHvJPtTU9h9Ol/GYM2r24MW,iv:zDulR59UG1Jcnc//Er2sCI3BH73ak4wplaa0BHnJgSo=,tag:4hfezf6UwmXhc9HpXFym+w==,type:str]
    SMTP_PASS: ENC[AES256_GCM,data:KbCmCczfqMo8McS4Z8xA,iv:U6miSfXSuFAKdkUPUKcD+n2quxk0jTg4zBumjrm+Jxg=,tag:1DCDSA4xZOo2j5pbGl9jdw==,type:str]
    SMTP_RECIPIENT: ENC[AES256_GCM,data:1rDrY/136X65xk40hPmndw==,iv:U6e5T1PvUZQXdKaxA5Ad7WDcLMgaR7y3R+XCm9h3no0=,tag:H5kx8Ko7+//17nyIooomUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEU0Q2WXhFZ3BLdGF0Nys2
            MWNXQzltM1RJOTFNZ1NyL0xlNVh0aFYwcWxNCm1YUGlHWXhXSDI4Mkgyc3JEc3VM
            dURHeE0wbWlDMGlwZmhRaEtkZExJa1kKLS0tIDdGclJZRkpUd1c3a3VCTm5RZG55
            NWFSQTB6UThyUVkrWGtvK3FLeVhNUUEKEt+DJH9TBC/zxl4UZIBHXc0sD9gffVtu
            xE1oWD9kGE6uBcIKJnPh6iXgMTOOPHjRxB7Dz3a7EXpVhadmWx/w6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T21:43:02Z"
    mac: ENC[AES256_GCM,data:CLwPZm3UGFRQ9z+BhyHyLzjsqvDr9uNnY8DBu/ZfVGcFVSE7y4+HxHf0YaYdprAg05//HS8gFXIZYelTnUl4wQ3ssScWaoATf7bse3X1DYswBmkQj7Vw3osBKv7MBPrEjUE/ExtFJYdLqSuzwS4GJp+Zjtm6sNHCiI3rTmkin4Q=,iv:AWPLwBqV15Dr+14uz2RrFUJUlrB5WcEm/hH9wOFgqtI=,tag:FTutcqAab/rfexyGVrDEhg==,type:str]
    version: 3.13.3
