apiVersion: v1
kind: Secret
metadata:
    name: aquilla-website-smtp
    namespace: aquilla-website
stringData:
    SMTP_HOST: ENC[AES256_GCM,data:LlZnD5sCeus5ss3t0f0Z8w==,iv:jyEuTSM9viUnXptnva/pNzpmGQRZzpPE+MJoHV4ZNf4=,tag:gavhaRO2z7WYR0VNbAe4ZA==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:b2vj,iv:sFXNnZMj8wRdqHkPOYmQv23bF8nGYb1DsdmXizJOIV4=,tag:Hrtd8PiFRNTKraejt9AbtQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:FQj0DnRO7fw7HP1WBDnKoPEs,iv:Fok6lfx8FtIfisHMS2kMNiQFTwt6xRLt5wSaLIRWRBk=,tag:Rv1OOxQPWS1bQ8tlQ5Tt8g==,type:str]
    SMTP_PASS: ENC[AES256_GCM,data:jC5N9/bfxu/1KMoynQD53A==,iv:kZoSymUOkkF3EDdyv6JTKpXsYkGjeXAPiipnJkDhfm8=,tag:r63hhWHQHU5YKBVWSUotUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcnp1MVJXQjMxTDZ6cE5R
            bWtZNVBZWnFuem03WVlWOWJMcFZTZU5sYXk4CkFLcGR6dUR6cDdDVWZST3cxcUg1
            UFp3SHlQK1d3ZUxUeUVTTEtiUTNLWkUKLS0tIDFLNmJxak5LYlFTdTVhdkpya2RR
            RVB5dm9iRXpTVkxKVDEwQXJCTUxzTmMK26NJk4WOOczxLOeg+lZTKtHfjkMWySFn
            y5t0KkGpnllNowYyRR1MdgUdwLOE5/UlC+FlC3iye3JDMazJyoyxJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T00:49:57Z"
    mac: ENC[AES256_GCM,data:UKSTTKJ7jYXsd/Ai+15nrEkUqEMb8Ivf76NtxuFJVlPbEBGqRASLUiZf96vOFpM2LA86J8ikzxxDQ5MqXTbpKaGB+CrirYw6B9sKQ7a7CazdiDqZQzbQUYDTNEvrPhuRY7U9siTIpLd6AvIKXQMmnCgUZVdtiI6F2BGGM9zlPMI=,iv:uAwAD1b3PwfnAsfUlhU5U/ymB45CIkKYWBzEW/F/dGk=,tag:941A4W2VI/3XjjSY5450hQ==,type:str]
    version: 3.13.2
