apiVersion: v1
kind: Secret
metadata:
    name: aquilla-website-smtp
    namespace: aquilla-website
stringData:
    SMTP_HOST: ENC[AES256_GCM,data:du1kdEy+1ZGRJ/NnM0ZWOU2UiQ==,iv:4BIYChEhWDM/8Z5gfzkMd1sTnhy1ZR1We8gnm6C8YfI=,tag:IhAT5/K5UlxH79vXPDw3Ug==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:b2vj,iv:sFXNnZMj8wRdqHkPOYmQv23bF8nGYb1DsdmXizJOIV4=,tag:Hrtd8PiFRNTKraejt9AbtQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:FQj0DnRO7fw7HP1WBDnKoPEs,iv:Fok6lfx8FtIfisHMS2kMNiQFTwt6xRLt5wSaLIRWRBk=,tag:Rv1OOxQPWS1bQ8tlQ5Tt8g==,type:str]
    SMTP_PASS: ENC[AES256_GCM,data:H36sbUrBud2AkHyhIliOY9Kf8MQ=,iv:84qHOyyj6O3yTUs9PoiCdt+YqDNm5py0VFNdj2I2tGs=,tag:ndU6y680bZKu3P2lZtbO+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcnp1MVJXQjMxTDZ6cE5R
            bWtZNVBZWnFuem03WVlWOWJMcFZTZU5sYXk4CkFLcGR6dUR6cDdDVWZST3cxcUg1
            UFp3SHlQK1d3ZUxUeUVTTEtiUTNLWkUKLS0tIDFLNmJxak5LYlFTdTVhdkpya2RR
            RVB5dm9iRXpTVkxKVDEwQXJCTUxzTmMK26NJk4WOOczxLOeg+lZTKtHfjkMWySFn
            y5t0KkGpnllNowYyRR1MdgUdwLOE5/UlC+FlC3iye3JDMazJyoyxJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T21:43:01Z"
    mac: ENC[AES256_GCM,data:E3RUhfII5cCWuBWyabafxD4Nwj87SW4JDJVyxwXQGOBZsArrgiKebZDhCuCc/bK8+2WBn3d6FgI5NJMHLvG0aZq5aewenWBF4DtrhGE0eTBOvMNehCZ2QMQXSbR6JlRLCZP3m4wwfZmTPYPh2JOqQnnDevY1VngZJudPMjLI52o=,iv:KvJb8nHvgc4QqSJywApysqn9XnoVf7E4WZcicrTL844=,tag:6pZELk0QFlZ1TBvXkcW1GA==,type:str]
    version: 3.13.2
