apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: perforce
resources:
  - namespace.yaml
  - pull.secret.yaml     # docker-registry cred for registry.aquilla.dev (SOPS)
  - secret.yaml          # P4PASSWD (SOPS)
  - statefulset.yaml
  - service.yaml
  - certificate.yaml
  - ingressroutetcp.yaml
#  - backup.yaml
