apiVersion: v1
kind: Secret
metadata:
    name: registry-pull
    namespace: perforce
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:sajpo67cRLcFZG2aYfEZtoLny3sPIr/3giQisGMruXRMVl7d3x00o36otigsQdTLxjtBqa5eYXBgbNZZ1YnVQCJFUVC0aDGJKjs=,iv:EA3YSurtaPad0wnaGzRH5XMt0j0eA1qUv9RJsg/Hq8Y=,tag:Vpo/63Kt+8kMi6M+PfTZ5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlU0lRMUo1YlFtdEpYMWJj
            NE9idzhuTTFVR2dkbmpWZVJTN1lHS0JzVkZFCjlFR1RCZ3d6RmgzaEhRM0hDMnhw
            eS81TjN3N2ZYWSs5QXhSNDYvRlcwb0kKLS0tIGNMTm5aTENlUml3VlY5Uy9ma2Fi
            d0xYQ0RLNWVMeHVXbitVbHFFcTlTTVEKS8ovuYfyEid2vyxnckhDmlsWEX31dY6y
            3OSnY9aSOCUaJltXsy/LD9sZAPPBgjto1c8Qr4F7gx1jEYSGKAlp/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T00:22:31Z"
    mac: ENC[AES256_GCM,data:fYg87FvBIScS4GxXHA/b1DFJXsTkJK0UcAwni6Ub5JeAXl9zyJB2lus1GrVFrFg6Mxyqv9/7AL3PjM13TAflhzVRRxDtW1LKqzkDHmiFQrm/MNHxSs9+ZR+Zn+8mClPMW8BUXx/h3jvn8Io9436HgRS4+gopoDbb2NlfxuUFMGE=,iv:SIfvU8UZIleBiseGw9KrNYBd+w0W/mSNyQt0qhvx/gc=,tag:wsHgg2kT5sQRsVk1Glx8SQ==,type:str]
    version: 3.13.2
