# P4PASSWD only for now; borg-credentials joins when backup.yaml is enabled.
apiVersion: v1
data:
    P4PASSWD: ENC[AES256_GCM,data:rhIzHK4brWzmVETozkeBcBvTinVZp1n77YG3gw==,iv:pu13YdQFwlFphNQuN59ZOgQdFoVCyfcOZrO4YZ55Rtc=,tag:UQhL51m4c/CugXa5Jd4QLw==,type:str]
kind: Secret
metadata:
    name: perforce-secret
    namespace: perforce
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTTdQVzVxNVI4cmlRM1JO
            QlFEMUV6cW1PekQ4VjFSMmhSdGNGL0FKaGlRCjdtV2c4TENwUzJCa3dXOHhRM1Vy
            Zy9idHAvS3A3RTJFSjdYRDhqNjBsUHcKLS0tIGU0b2E4OTh3SmdMRlN2dnp0UVRu
            YnBITlFZeWEyYVFERXNHMy9ZMFlTb3MK0qDBIGof/xWrCPeRBtqy+GwUk6xaDzHC
            Or1mWBwagDXpnN8MntS5DA/rUXx0RGJedf+34VymoRpG/nDaCIZdpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T10:59:48Z"
    mac: ENC[AES256_GCM,data:oRSOtwayMPet5do7tEJ7lANlNVhflOJcgGUM5MygNmRhXUVF1scLHFRasotzOEEQ46HtvaaXaRQBCvndhJDZWJ7Em5jOGXuHg/tCI6WO4HOrHsfYStSLKhf2UPKh+eHdfWg19OEytErP+Tc35EVcMF1MgS8L2euYYEQL25HnnEE=,iv:cm1ttZdOo/O1wzw8H9JyyaDv84HvUoibje7d1a+9Mvs=,tag:zZ9oournbb+H7vyQ6aN9fQ==,type:str]
    version: 3.13.2
