# P4PASSWD only for now; borg-credentials joins when backup.yaml is enabled.
apiVersion: v1
kind: Secret
metadata:
    name: perforce-secret
    namespace: perforce
type: Opaque
stringData:
    P4PASSWD: ENC[AES256_GCM,data:p9u0xVKylI8VyFoWq6GnJnbv9hcqBMI=,iv:O/Wf7UrLhgEWcvFvUiRP+il/v8Ybxn11ezJ5A3wJIf0=,tag:pjaJDo9hwwg1tlzoFw7xhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcXlicUNxaTRjUzdzU05Y
            ZytlSUxIekFuZTN6OG0wUHZ2Z0dBZnBwakFRClM0ZFVqVzYrU2dhTmxYaVlOc3BJ
            MHR2NThkdHNTUEtXMDhuenBOZWd6TXcKLS0tIHBDeGpIVVU4N3BwN0hOQmp6bE41
            ZUZFclgxU01VUExJZS9lT3BPYXVMUDQKXkeNOfUWJpWh60FILSX2vQcX7PUFKEPM
            xuYnT3Ngfe3lMVEkimWQzja6ACnCD7yUfctjAQ7XfrzFiVCunPhjZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T00:49:57Z"
    mac: ENC[AES256_GCM,data:85g7wngrsUZ9g7NrMQXf6i0Npn4H6p8GtFLYz3G0mS23hH+vMI3t6TjYfmTwIU7olu/0lSBpheKXk8srD7c6r7jqm25wlP+9GxlPNZxt8yTRtcJL4kVr3te/4DiLmuL+tFbYV6Ba2lv0QFBR0AE8sUPBLZxp7FkoytIqRrXbUL8=,iv:vCIETO8cKKLDJBWOCk9k15wRnMsj1DsjW78uO/7EfSk=,tag:7DeB/OyK7TlDxE0tS39LtA==,type:str]
    version: 3.13.2
