apiVersion: v1
kind: Service
metadata:
  name: p4d
  namespace: perforce
spec:
  selector:
    app: p4d
  ports:
    - name: p4d
      port: 1666
      targetPort: 1666
  clusterIP: None        # headless, matches the StatefulSet
