/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.io.javaoperatorsdk.operator.framework)
    api(libs.org.slf4j.slf4j.api)
    api(libs.org.apache.logging.log4j.log4j.slf4j2.impl)
    api(libs.org.apache.logging.log4j.log4j.core)
    testImplementation(libs.io.javaoperatorsdk.operator.framework.junit)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)

    // Source: https://mvnrepository.com/artifact/io.fabric8/crd-generator-apt
    implementation("io.fabric8:crd-generator-apt:7.8.0")

    compileOnly("org.projectlombok:lombok:1.18.36")
    annotationProcessor("org.projectlombok:lombok:1.18.36")
}

group = "io.davud"
version = "0.1.0-SNAPSHOT"
description = "sample-webpage-operator"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
