apiVersion: v1
data:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:GxrUV3k2eFl/BLcFLVPBCul3diyFukBmQvlGpXfICr6lt0M4SR0Ak+GDnBmI/CnKmph8vnoKjtSR3xH2acD/OklbVWspHEDzdQxeRXBfj7kIpshH66hheoj07KGVAIW0dis2sk5hWwaq5MBlmd6As2eTQDvqxZ7rAmqmq+g8W4h9vcAYIt+SmNwiUgqfXEH/p174pgXfGidusxMUczKT8ED7oAc2mEyld34LBaX8yiRnFbt/wJSTzUdO8idlqF+60tomZWTf2pVUQG29zLyK6Lr/Obku7LZI2qjOqnpH0WbZjvZg5cmxt+bAM138AjvxM9wADS3Gzhk=,iv:gy2qnpnmVCVmTkuOv2dpX+GadBtLy5YrYdkEwwCMiaI=,tag:Uk9vQyzR6RNg1dIdkNdJog==,type:str]
kind: Secret
metadata:
    name: livesync-secret
    namespace: livesync
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbG9DRGErMTFwTys0V1c3
            Qmw3VnhNZlpETnk3eWE0VjR4VGtqYUtYdkhBCldsamhQOWZiWXdjdFQweStnd3dN
            TVkyNm1OK0d6dmVNYWpMd09WNjRhNjQKLS0tIEw2WXc2bGhiNHdUWU55Z2U1enJO
            a0ZTd0V5bTNxQ2w0QkpEK21aaGUyU1EKF4yF2LX5jJVwqGYDRyoGDnLzuRhcgsu6
            4/y9q3Xzc/3FcJV0n93cIs7+3G3aNhBaZ4oh0UQi/1q8mj9A3dU0EQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T10:41:25Z"
    mac: ENC[AES256_GCM,data:jd7o2R+8F8vxHJGVvAyGVdGuhg52vlpIOMoFqzMhYrwP+HrWgbgGkU8epML5vtIzwE2nk994zNCfdmgi6QmOQjgyZajjQCfcP0tFSSw5DXE7LIKzMM9FEdhLbhkQbvDsF3KJYrthUJBpv9fCd2kpWOcBFLKumiOpeKVCJ4lEbcE=,iv:OWhn/Vd/tG+DOvQvikf1ZeVBC9wPRvJnSVZUKBLc+88=,tag:8Lnn7/17Zi29/Ri9UScNAg==,type:str]
    version: 3.13.2
