apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: taida-portfolio
resources:
  - namespace.yaml
  - pull.secret.yaml     # docker-registry cred for registry.aquilla.dev (SOPS)
  - helmrelease.yaml     # website chart: flux/charts/website
