apiVersion: v1
kind: Secret
metadata:
    name: registry-pull
    namespace: taida-portfolio
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:8ZJDTGRwpSkUB7skYNqpv46EB0sKsRU6TnHhK6WbIqHoCGfcWS5rDKefC10Mh0l3bTdZYw98nVpYrtT4EVakV8q2UB4dYK5+wpI=,iv:hErGIZUfmOrl4+Ix+zszU1/l4WP0RIEH4OS1325W+CQ=,tag:GCj7Vnh1bcPdBvI5jo6vAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTHJxaDdSekxQeFhrMmho
            bG01bDZKK1hoOUU3dHJGYU1PaFhKN1VTU25JCkF1Z0ZrNVA5eU9ERUVXTnRYZmJo
            dExtVzhYKzF3T1U1QXJENTNmWGhOSDgKLS0tIC9qditBa2hxaml1M2dQV0YvV0Zu
            RytzRlJwdzVPcFVuVWJpU3h1eG85NUkK1dQfbc8z89wOLBOPqdjXRL206sfNnqrb
            rDH19KG8C3HO+FP6qmPWz/TlAdXHaXx05pcC+eVerzMSoTvVpIUCSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13crn4t6762vdxz3jthwyw4qxjutuknydnr677g3mqzuf8xy0r53smjtway
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T00:49:57Z"
    mac: ENC[AES256_GCM,data:4tGhX27QoREyfNQDHahyvTX0sDj4Zy9/A/ZBOTcWcBXtFVvWZCCpwVxHy0z/bcakUsmLxN61F2aY9tDO2cS05QHiZ3L+D8Qk0n7Ee2zm/JGL96jhdryNbrcEmRyJQdfPwKKe2/EhZxCboWzPixggvZJTkHZq+5xoKfN3X6zGM+Y=,iv:W0UZuTJr2fU7qarjxlQYYolGmu04ZGHSJH1ZeyGB0G0=,tag:DykAgS4/TzhKQU1kljcggQ==,type:str]
    version: 3.13.2
